-- Add stock columns to raw materials tables
ALTER TABLE public.coffee_types ADD COLUMN stock_kg numeric DEFAULT 0;
ALTER TABLE public.additives ADD COLUMN stock_grams numeric DEFAULT 0;

-- Create the purchases table to log all incoming stock
CREATE TABLE public.purchases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    item_type text NOT NULL, -- 'coffee' or 'additive'
    item_code text NOT NULL, -- Corresponds to coffee_types.code or additives.id
    quantity numeric NOT NULL, -- in KG for coffee, in Grams for additives
    cost numeric NOT NULL,
    supplier text,
    notes text
);

-- Enable RLS for the new table
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;

-- Create policies for the purchases table
CREATE POLICY "Admins can manage all purchases"
ON public.purchases FOR ALL
USING (get_user_role() = 'admin'::text)
WITH CHECK (get_user_role() = 'admin'::text);