-- حذف التوليفات التركية الحالية لمنع التكرار
DELETE FROM public.blends WHERE method_id = 'turkish';

-- إضافة 87 توليفة جديدة ببيانات عشوائية
INSERT INTO public.blends (name_ar, name_en, code, method_id, notes_ar, notes_en, sensory_profile, is_active) VALUES
('توليفة تركي 1', 'Turkish Blend 1', 'TR-001', 'turkish', 'هيل وقرنفل', 'Cardamom and Clove', '{"face": 4, "body": 5, "sweetness": 2, "bitterness": 3, "strength": 4, "aroma": 5}', true),
('توليفة تركي 2', 'Turkish Blend 2', 'TR-002', 'turkish', 'مكسرات محمصة', 'Toasted Nuts', '{"face": 5, "body": 4, "sweetness": 3, "bitterness": 4, "strength": 5, "aroma": 3}', true),
('توليفة تركي 3', 'Turkish Blend 3', 'TR-003', 'turkish', 'شوكولاتة داكنة', 'Dark Chocolate', '{"face": 3, "body": 5, "sweetness": 4, "bitterness": 5, "strength": 4, "aroma": 4}', true),
('توليفة تركي 4', 'Turkish Blend 4', 'TR-004', 'turkish', 'توابل دافئة', 'Warm Spices', '{"face": 4, "body": 3, "sweetness": 3, "bitterness": 2, "strength": 3, "aroma": 5}', true),
('توليفة تركي 5', 'Turkish Blend 5', 'TR-005', 'turkish', 'لمسة فاكهية', 'Fruity Touch', '{"face": 2, "body": 3, "sweetness": 5, "bitterness": 2, "strength": 3, "aroma": 4}', true),
('توليفة تركي 6', 'Turkish Blend 6', 'TR-006', 'turkish', 'قوام كريمي', 'Creamy Body', '{"face": 5, "body": 5, "sweetness": 3, "bitterness": 3, "strength": 4, "aroma": 4}', true),
('توليفة تركي 7', 'Turkish Blend 7', 'TR-007', 'turkish', 'مرارة متوازنة', 'Balanced Bitterness', '{"face": 4, "body": 4, "sweetness": 4, "bitterness": 3, "strength": 4, "aroma": 3}', true),
('توليفة تركي 8', 'Turkish Blend 8', 'TR-008', 'turkish', 'نكهة قوية', 'Strong Flavor', '{"face": 3, "body": 4, "sweetness": 2, "bitterness": 4, "strength": 5, "aroma": 4}', true),
('توليفة تركي 9', 'Turkish Blend 9', 'TR-009', 'turkish', 'رائحة فواحة', 'Aromatic Scent', '{"face": 4, "body": 3, "sweetness": 4, "bitterness": 2, "strength": 3, "aroma": 5}', true),
('توليفة تركي 10', 'Turkish Blend 10', 'TR-010', 'turkish', 'حلاوة طبيعية', 'Natural Sweetness', '{"face": 3, "body": 4, "sweetness": 5, "bitterness": 2, "strength": 4, "aroma": 4}', true),
('توليفة تركي 11', 'Turkish Blend 11', 'TR-011', 'turkish', 'وش كثيف', 'Thick Foam', '{"face": 5, "body": 4, "sweetness": 3, "bitterness": 3, "strength": 4, "aroma": 3}', true),
('توليفة تركي 12', 'Turkish Blend 12', 'TR-012', 'turkish', 'قوام ممتلئ', 'Full Body', '{"face": 4, "body": 5, "sweetness": 3, "bitterness": 4, "strength": 5, "aroma": 4}', true),
('توليفة تركي 13', 'Turkish Blend 13', 'TR-013', 'turkish', 'نكهة كلاسيكية', 'Classic Flavor', '{"face": 4, "body": 4, "sweetness": 3, "bitterness": 3, "strength": 4, "aroma": 4}', true),
('توليفة تركي 14', 'Turkish Blend 14', 'TR-014', 'turkish', 'لمسة من الحمضيات', 'Hint of Citrus', '{"face": 2, "body": 3, "sweetness": 5, "bitterness": 2, "strength": 3, "aroma": 5}', true),
('توليفة تركي 15', 'Turkish Blend 15', 'TR-015', 'turkish', 'نهاية نظيفة', 'Clean Finish', '{"face": 3, "body": 3, "sweetness": 4, "bitterness": 2, "strength": 3, "aroma": 4}', true),
('توليفة تركي 16', 'Turkish Blend 16', 'TR-016', 'turkish', 'قوية وغنية', 'Strong and Rich', '{"face": 4, "body": 5, "sweetness": 2, "bitterness": 5, "strength": 5, "aroma": 4}', true),
('توليفة تركي 17', 'Turkish Blend 17', 'TR-017', 'turkish', 'خفيفة ومنعشة', 'Light and Refreshing', '{"face": 3, "body": 2, "sweetness": 4, "bitterness": 1, "strength": 2, "aroma": 4}', true),
('توليفة تركي 18', 'Turkish Blend 18', 'TR-018', 'turkish', 'ترابية وعميقة', 'Earthy and Deep', '{"face": 4, "body": 5, "sweetness": 1, "bitterness": 4, "strength": 5, "aroma": 3}', true),
('توليفة تركي 19', 'Turkish Blend 19', 'TR-019', 'turkish', 'زهرية وعطرية', 'Floral and Aromatic', '{"face": 3, "body": 3, "sweetness": 4, "bitterness": 2, "strength": 3, "aroma": 5}', true),
('توليفة تركي 20', 'Turkish Blend 20', 'TR-020', 'turkish', 'متوازنة وسلسة', 'Balanced and Smooth', '{"face": 4, "body": 4, "sweetness": 3, "bitterness": 3, "strength": 4, "aroma": 4}', true),
('توليفة تركي 21', 'Turkish Blend 21', 'TR-021', 'turkish', 'هيل واضح', 'Pronounced Cardamom', '{"face": 3, "body": 4, "sweetness": 2, "bitterness": 3, "strength": 4, "aroma": 5}', true),
('توليفة تركي 22', 'Turkish Blend 22', 'TR-022', 'turkish', 'مذاق مكسرات', 'Nutty Taste', '{"face": 4, "body": 4, "sweetness": 3, "bitterness": 4, "strength": 4, "aroma": 3}', true),
('توليفة تركي 23', 'Turkish Blend 23', 'TR-023', 'turkish', 'حلاوة الكراميل', 'Caramel Sweetness', '{"face": 4, "body": 5, "sweetness": 5, "bitterness": 3, "strength": 4, "aroma": 4}', true),
('توليفة تركي 24', 'Turkish Blend 24', 'TR-024', 'turkish', 'توابل شرقية', 'Oriental Spices', '{"face": 3, "body": 3, "sweetness": 3, "bitterness": 2, "strength": 3, "aroma": 5}', true),
('توليفة تركي 25', 'Turkish Blend 25', 'TR-025', 'turkish', 'فاكهة مجففة', 'Dried Fruit', '{"face": 2, "body": 4, "sweetness": 5, "bitterness": 2, "strength": 4, "aroma": 4}', true),
('توليفة تركي 26', 'Turkish Blend 26', 'TR-026', 'turkish', 'قوام ثقيل', 'Heavy Body', '{"face": 5, "body": 5, "sweetness": 2, "bitterness": 4, "strength": 5, "aroma": 3}', true),
('توليفة تركي 27', 'Turkish Blend 27', 'TR-027', 'turkish', 'مرارة لطيفة', 'Gentle Bitterness', '{"face": 4, "body": 4, "sweetness": 4, "bitterness": 2, "strength": 4, "aroma": 4}', true),
('توليفة تركي 28', 'Turkish Blend 28', 'TR-028', 'turkish', 'نكهة مكثفة', 'Intense Flavor', '{"face": 3, "body": 5, "sweetness": 2, "bitterness": 5, "strength": 5, "aroma": 4}', true),
('توليفة تركي 29', 'Turkish Blend 29', 'TR-029', 'turkish', 'رائحة خشبية', 'Woody Aroma', '{"face": 4, "body": 4, "sweetness": 2, "bitterness": 3, "strength": 4, "aroma": 3}', true),
('توليفة تركي 30', 'Turkish Blend 30', 'TR-030', 'turkish', 'حلاوة العسل', 'Honey Sweetness', '{"face": 3, "body": 3, "sweetness": 5, "bitterness": 1, "strength": 3, "aroma": 4}', true),
('توليفة تركي 31', 'Turkish Blend 31', 'TR-031', 'turkish', 'وش خفيف', 'Light Foam', '{"face": 2, "body": 3, "sweetness": 4, "bitterness": 2, "strength": 3, "aroma": 4}', true),
('توليفة تركي 32', 'Turkish Blend 32', 'TR-032', 'turkish', 'قوام حريري', 'Silky Body', '{"face": 4, "body": 5, "sweetness": 4, "bitterness": 3, "strength": 4, "aroma": 5}', true),
('توليفة تركي 33', 'Turkish Blend 33', 'TR-033', 'turkish', 'نكهة معقدة', 'Complex Flavor', '{"face": 3, "body": 4, "sweetness": 4, "bitterness": 4, "strength": 5, "aroma": 5}', true),
('توليفة تركي 34', 'Turkish Blend 34', 'TR-034', 'turkish', 'حمضية مشرقة', 'Bright Acidity', '{"face": 2, "body": 3, "sweetness": 5, "bitterness": 2, "strength": 3, "aroma": 4}', true),
('توليفة تركي 35', 'Turkish Blend 35', 'TR-035', 'turkish', 'نهاية طويلة', 'Long Finish', '{"face": 4, "body": 5, "sweetness": 3, "bitterness": 4, "strength": 5, "aroma": 4}', true),
('توليفة تركي 36', 'Turkish Blend 36', 'TR-036', 'turkish', 'قوية جدا', 'Very Strong', '{"face": 4, "body": 5, "sweetness": 1, "bitterness": 5, "strength": 5, "aroma": 3}', true),
('توليفة تركي 37', 'Turkish Blend 37', 'TR-037', 'turkish', 'خفيفة جدا', 'Very Light', '{"face": 2, "body": 2, "sweetness": 4, "bitterness": 1, "strength": 2, "aroma": 3}', true),
('توليفة تركي 38', 'Turkish Blend 38', 'TR-038', 'turkish', 'ترابية مدخنة', 'Earthy and Smoky', '{"face": 4, "body": 5, "sweetness": 1, "bitterness": 4, "strength": 5, "aroma": 2}', true),
('توليفة تركي 39', 'Turkish Blend 39', 'TR-039', 'turkish', 'عطرية فواحة', 'Very Aromatic', '{"face": 3, "body": 3, "sweetness": 4, "bitterness": 2, "strength": 3, "aroma": 5}', true),
('توليفة تركي 40', 'Turkish Blend 40', 'TR-040', 'turkish', 'متوازنة تماما', 'Perfectly Balanced', '{"face": 4, "body": 4, "sweetness": 3, "bitterness": 3, "strength": 4, "aroma": 4}', true),
('توليفة تركي 41', 'Turkish Blend 41', 'TR-041', 'turkish', 'قرنفل وتوابل', 'Clove and Spices', '{"face": 3, "body": 4, "sweetness": 2, "bitterness": 4, "strength": 4, "aroma": 5}', true),
('توليفة تركي 42', 'Turkish Blend 42', 'TR-042', 'turkish', 'مذاق اللوز', 'Almond Taste', '{"face": 4, "body": 4, "sweetness": 3, "bitterness": 3, "strength": 4, "aroma": 3}', true),
('توليفة تركي 43', 'Turkish Blend 43', 'TR-043', 'turkish', 'حلاوة التمر', 'Date Sweetness', '{"face": 4, "body": 5, "sweetness": 5, "bitterness": 3, "strength": 4, "aroma": 4}', true),
('توليفة تركي 44', 'Turkish Blend 44', 'TR-044', 'turkish', 'قرفة وزنجبيل', 'Cinnamon and Ginger', '{"face": 3, "body": 3, "sweetness": 3, "bitterness": 2, "strength": 4, "aroma": 5}', true),
('توليفة تركي 45', 'Turkish Blend 45', 'TR-045', 'turkish', 'توت بري', 'Wild Berries', '{"face": 2, "body": 3, "sweetness": 5, "bitterness": 2, "strength": 3, "aroma": 4}', true),
('توليفة تركي 46', 'Turkish Blend 46', 'TR-046', 'turkish', 'قوام غني جدا', 'Very Rich Body', '{"face": 5, "body": 5, "sweetness": 2, "bitterness": 4, "strength": 5, "aroma": 3}', true),
('توليفة تركي 47', 'Turkish Blend 47', 'TR-047', 'turkish', 'مرارة الشوكولاتة', 'Chocolate Bitterness', '{"face": 4, "body": 5, "sweetness": 3, "bitterness": 5, "strength": 5, "aroma": 4}', true),
('توليفة تركي 48', 'Turkish Blend 48', 'TR-048', 'turkish', 'نكهة جريئة', 'Bold Flavor', '{"face": 3, "body": 5, "sweetness": 2, "bitterness": 5, "strength": 5, "aroma": 4}', true),
('توليفة تركي 49', 'Turkish Blend 49', 'TR-049', 'turkish', 'رائحة دخانية', 'Smoky Aroma', '{"face": 4, "body": 5, "sweetness": 1, "bitterness": 4, "strength": 5, "aroma": 2}', true),
('توليفة تركي 50', 'Turkish Blend 50', 'TR-050', 'turkish', 'حلاوة الفانيلا', 'Vanilla Sweetness', '{"face": 3, "body": 4, "sweetness": 5, "bitterness": 2, "strength": 4, "aroma": 5}', true),
('توليفة تركي 51', 'Turkish Blend 51', 'TR-051', 'turkish', 'وش متوسط', 'Medium Foam', '{"face": 3, "body": 4, "sweetness": 3, "bitterness": 3, "strength": 4, "aroma": 4}', true),
('توليفة تركي 52', 'Turkish Blend 52', 'TR-052', 'turkish', 'قوام متوسط', 'Medium Body', '{"face": 4, "body": 3, "sweetness": 3, "bitterness": 3, "strength": 3, "aroma": 4}', true),
('توليفة تركي 53', 'Turkish Blend 53', 'TR-053', 'turkish', 'نكهة متوازنة', 'Balanced Flavor', '{"face": 4, "body": 4, "sweetness": 4, "bitterness": 3, "strength": 4, "aroma": 4}', true),
('توليفة تركي 54', 'Turkish Blend 54', 'TR-054', 'turkish', 'حمضية خفيفة', 'Light Acidity', '{"face": 3, "body": 3, "sweetness": 4, "bitterness": 2, "strength": 3, "aroma": 3}', true),
('توليفة تركي 55', 'Turkish Blend 55', 'TR-055', 'turkish', 'نهاية قصيرة', 'Short Finish', '{"face": 3, "body": 4, "sweetness": 3, "bitterness": 4, "strength": 4, "aroma": 3}', true),
('توليفة تركي 56', 'Turkish Blend 56', 'TR-056', 'turkish', 'قوية جدا ومرة', 'Very Strong and Bitter', '{"face": 4, "body": 5, "sweetness": 1, "bitterness": 5, "strength": 5, "aroma": 2}', true),
('توليفة تركي 57', 'Turkish Blend 57', 'TR-057', 'turkish', 'خفيفة وحلوة', 'Light and Sweet', '{"face": 2, "body": 2, "sweetness": 5, "bitterness": 1, "strength": 2, "aroma": 4}', true),
('توليفة تركي 58', 'Turkish Blend 58', 'TR-058', 'turkish', 'ترابية خفيفة', 'Lightly Earthy', '{"face": 3, "body": 4, "sweetness": 2, "bitterness": 3, "strength": 4, "aroma": 3}', true),
('توليفة تركي 59', 'Turkish Blend 59', 'TR-059', 'turkish', 'عطرية خفيفة', 'Lightly Aromatic', '{"face": 3, "body": 3, "sweetness": 4, "bitterness": 2, "strength": 3, "aroma": 4}', true),
('توليفة تركي 60', 'Turkish Blend 60', 'TR-060', 'turkish', 'متوازنة وناعمة', 'Balanced and Soft', '{"face": 4, "body": 4, "sweetness": 4, "bitterness": 2, "strength": 4, "aroma": 4}', true),
('توليفة تركي 61', 'Turkish Blend 61', 'TR-061', 'turkish', 'هيل خفيف', 'Subtle Cardamom', '{"face": 3, "body": 4, "sweetness": 3, "bitterness": 3, "strength": 4, "aroma": 4}', true),
('توليفة تركي 62', 'Turkish Blend 62', 'TR-062', 'turkish', 'مذاق البندق', 'Hazelnut Taste', '{"face": 4, "body": 4, "sweetness": 4, "bitterness": 3, "strength": 4, "aroma": 3}', true),
('توليفة تركي 63', 'Turkish Blend 63', 'TR-063', 'turkish', 'حلاوة الفاكهة', 'Fruit Sweetness', '{"face": 3, "body": 4, "sweetness": 5, "bitterness": 2, "strength": 4, "aroma": 5}', true),
('توليفة تركي 64', 'Turkish Blend 64', 'TR-064', 'turkish', 'توابل خفيفة', 'Mild Spices', '{"face": 3, "body": 3, "sweetness": 3, "bitterness": 2, "strength": 3, "aroma": 4}', true),
('توليفة تركي 65', 'Turkish Blend 65', 'TR-065', 'turkish', 'كرز أسود', 'Black Cherry', '{"face": 2, "body": 4, "sweetness": 5, "bitterness": 3, "strength": 4, "aroma": 4}', true),
('توليفة تركي 66', 'Turkish Blend 66', 'TR-066', 'turkish', 'قوام كثيف', 'Dense Body', '{"face": 5, "body": 5, "sweetness": 3, "bitterness": 4, "strength": 5, "aroma": 3}', true),
('توليفة تركي 67', 'Turkish Blend 67', 'TR-067', 'turkish', 'مرارة الكاكاو', 'Cacao Bitterness', '{"face": 4, "body": 5, "sweetness": 2, "bitterness": 5, "strength": 5, "aroma": 4}', true),
('توليفة تركي 68', 'Turkish Blend 68', 'TR-068', 'turkish', 'نكهة عميقة', 'Deep Flavor', '{"face": 4, "body": 5, "sweetness": 2, "bitterness": 4, "strength": 5, "aroma": 4}', true),
('توليفة تركي 69', 'Turkish Blend 69', 'TR-069', 'turkish', 'رائحة التبغ', 'Tobacco Aroma', '{"face": 4, "body": 5, "sweetness": 1, "bitterness": 4, "strength": 5, "aroma": 2}', true),
('توليفة تركي 70', 'Turkish Blend 70', 'TR-070', 'turkish', 'حلاوة السكر البني', 'Brown Sugar Sweetness', '{"face": 4, "body": 4, "sweetness": 5, "bitterness": 2, "strength": 4, "aroma": 4}', true),
('توليفة تركي 71', 'Turkish Blend 71', 'TR-071', 'turkish', 'وش دائم', 'Lasting Foam', '{"face": 5, "body": 4, "sweetness": 3, "bitterness": 3, "strength": 4, "aroma": 3}', true),
('توليفة تركي 72', 'Turkish Blend 72', 'TR-072', 'turkish', 'قوام ناعم', 'Smooth Body', '{"face": 4, "body": 5, "sweetness": 4, "bitterness": 2, "strength": 4, "aroma": 4}', true),
('توليفة تركي 73', 'Turkish Blend 73', 'TR-073', 'turkish', 'نكهة غنية', 'Rich Flavor', '{"face": 4, "body": 5, "sweetness": 3, "bitterness": 4, "strength": 5, "aroma": 4}', true),
('توليفة تركي 74', 'Turkish Blend 74', 'TR-074', 'turkish', 'حمضية لطيفة', 'Gentle Acidity', '{"face": 3, "body": 3, "sweetness": 4, "bitterness": 1, "strength": 3, "aroma": 4}', true),
('توليفة تركي 75', 'Turkish Blend 75', 'TR-075', 'turkish', 'نهاية مميزة', 'Distinct Finish', '{"face": 4, "body": 4, "sweetness": 3, "bitterness": 4, "strength": 4, "aroma": 5}', true),
('توليفة تركي 76', 'Turkish Blend 76', 'TR-076', 'turkish', 'قوية ومرة جدا', 'Extremely Strong and Bitter', '{"face": 5, "body": 5, "sweetness": 1, "bitterness": 5, "strength": 5, "aroma": 2}', true),
('توليفة تركي 77', 'Turkish Blend 77', 'TR-077', 'turkish', 'خفيفة جدا وحلوة', 'Extremely Light and Sweet', '{"face": 1, "body": 2, "sweetness": 5, "bitterness": 1, "strength": 1, "aroma": 4}', true),
('توليفة تركي 78', 'Turkish Blend 78', 'TR-078', 'turkish', 'ترابية قوية', 'Strongly Earthy', '{"face": 4, "body": 5, "sweetness": 1, "bitterness": 4, "strength": 5, "aroma": 3}', true),
('توليفة تركي 79', 'Turkish Blend 79', 'TR-079', 'turkish', 'عطرية جدا', 'Extremely Aromatic', '{"face": 3, "body": 3, "sweetness": 4, "bitterness": 2, "strength": 3, "aroma": 5}', true),
('توليفة تركي 80', 'Turkish Blend 80', 'TR-080', 'turkish', 'متوازنة بشكل مثالي', 'Perfectly Balanced', '{"face": 5, "body": 5, "sweetness": 3, "bitterness": 3, "strength": 4, "aroma": 4}', true),
('توليفة تركي 81', 'Turkish Blend 81', 'TR-081', 'turkish', 'توابل قوية', 'Strong Spices', '{"face": 3, "body": 4, "sweetness": 2, "bitterness": 3, "strength": 5, "aroma": 5}', true),
('توليفة تركي 82', 'Turkish Blend 82', 'TR-082', 'turkish', 'مذاق الجوز', 'Walnut Taste', '{"face": 4, "body": 4, "sweetness": 2, "bitterness": 4, "strength": 4, "aroma": 3}', true),
('توليفة تركي 83', 'Turkish Blend 83', 'TR-083', 'turkish', 'حلاوة الشوكولاتة بالحليب', 'Milk Chocolate Sweetness', '{"face": 4, "body": 5, "sweetness": 5, "bitterness": 2, "strength": 4, "aroma": 4}', true),
('توليفة تركي 84', 'Turkish Blend 84', 'TR-084', 'turkish', 'توابل هندية', 'Indian Spices', '{"face": 3, "body": 4, "sweetness": 3, "bitterness": 3, "strength": 4, "aroma": 5}', true),
('توليفة تركي 85', 'Turkish Blend 85', 'TR-085', 'turkish', 'تين مجفف', 'Dried Fig', '{"face": 3, "body": 5, "sweetness": 5, "bitterness": 3, "strength": 4, "aroma": 4}', true),
('توليفة تركي 86', 'Turkish Blend 86', 'TR-086', 'turkish', 'قوام مخملي', 'Velvety Body', '{"face": 5, "body": 5, "sweetness": 4, "bitterness": 3, "strength": 5, "aroma": 4}', true),
('توليفة تركي 87', 'Turkish Blend 87', 'TR-087', 'turkish', 'مرارة منعشة', 'Refreshing Bitterness', '{"face": 4, "body": 4, "sweetness": 3, "bitterness": 4, "strength": 4, "aroma": 5}', true);