UPDATE public.blends SET name_ar = 'خان الخليلي', notes_ar = 'شوكولاتة داكنة - مكسرات محمصة - حلاوة التمر', name_en = 'Khan el-Khalili', notes_en = 'Dark chocolate - roasted nuts - date sweetness' WHERE code = 'TRK-001';
UPDATE public.blends SET name_ar = 'الزمالك', notes_ar = 'كراميل - زهور بيضاء - لمسة فاكهية', name_en = 'Zamalek', notes_en = 'Caramel - white flowers - fruity touch' WHERE code = 'TRK-002';
UPDATE public.blends SET name_ar = 'الجونا', notes_ar = 'شوكولاتة بالحليب - حلاوة الفانيليا - قرفة خفيفة', name_en = 'El Gouna', notes_en = 'Milk chocolate - vanilla sweetness - light cinnamon' WHERE code = 'TRK-003';
UPDATE public.blends SET name_ar = 'حدائق المنتزه', notes_ar = 'توت أسود - عسل - حمضية الليمون', name_en = 'Montaza Gardens', notes_en = 'Blackberry - honey - lemon acidity' WHERE code = 'TRB-201';
UPDATE public.blends SET name_ar = 'واحة سيوة', notes_ar = 'فواكه مجففة - قرفة - كاكاو', name_en = 'Siwa Oasis', notes_en = 'Dried fruits - cinnamon - cocoa' WHERE code = 'TRB-202';
UPDATE public.blends SET name_ar = 'المعز', notes_ar = 'كراميل - جوز - شوكولاتة بالحليب', name_en = 'El Moez', notes_en = 'Caramel - walnut - milk chocolate' WHERE code = 'TRB-203';
UPDATE public.blends SET name_ar = 'سهل حشيش', notes_ar = 'شوكولاتة بيضاء - فانيليا - جوز الهند', name_en = 'Sahl Hasheesh', notes_en = 'White chocolate - vanilla - coconut' WHERE code = 'TRB-204';
UPDATE public.blends SET name_ar = 'القرنة', notes_ar = 'مشمش - زهور - عسل السدر', name_en = 'El Qurna', notes_en = 'Apricot - flowers - sidr honey' WHERE code = 'TRB-205';
UPDATE public.blends SET name_ar = 'الحسين', notes_ar = 'مكسرات محمصة - تمر - شوكولاتة', name_en = 'El Hussein', notes_en = 'Roasted nuts - dates - chocolate' WHERE code = 'TRB-207';
UPDATE public.blends SET name_ar = 'أسوان', notes_ar = 'تين مجفف - توابل دافئة - كاكاو', name_en = 'Aswan', notes_en = 'Dried fig - warm spices - cocoa' WHERE code = 'TRB-208';
UPDATE public.blends SET name_ar = 'شالي', notes_ar = 'خوخ - شاي أسود - حلاوة العسل', name_en = 'Shali', notes_en = 'Peach - black tea - honey sweetness' WHERE code = 'TRB-210';
UPDATE public.blends SET name_ar = 'دهب', notes_ar = 'فواكه استوائية - كراميل - قوام غني', name_en = 'Dahab', notes_en = 'Tropical fruits - caramel - rich body' WHERE code = 'TRB-211';
UPDATE public.blends SET name_ar = 'الفيوم', notes_ar = 'كمثرى - فانيليا - لمسة دخانية', name_en = 'Faiyum', notes_en = 'Pear - vanilla - smoky touch' WHERE code = 'TRB-212';
UPDATE public.blends SET name_ar = 'الأقصر', notes_ar = 'قرفة - كراميل - جوز الهند المحمص', name_en = 'Luxor', notes_en = 'Cinnamon - caramel - toasted coconut' WHERE code = 'TRB-213';
UPDATE public.blends SET name_ar = 'الساحل الشمالي', notes_ar = 'حمضيات - عسل أبيض - زهور', name_en = 'North Coast', notes_en = 'Citrus - white honey - flowers' WHERE code = 'TRB-214';
UPDATE public.blends SET name_ar = 'فيلة', notes_ar = 'مشمش مجفف - برقوق - حلاوة فاكهية', name_en = 'Philae', notes_en = 'Dried apricot - plum - fruity sweetness' WHERE code = 'TRB-215';
UPDATE public.blends SET name_ar = 'مصر القديمة', notes_ar = 'تمر - كاكاو خام - توابل شرقية', name_en = 'Old Cairo', notes_en = 'Dates - raw cocoa - oriental spices' WHERE code = 'TRB-216';
UPDATE public.blends SET name_ar = 'هليوبوليس', notes_ar = 'توت أسود - فستق - شوكولاتة', name_en = 'Heliopolis', notes_en = 'Blackberry - pistachio - chocolate' WHERE code = 'TRB-217';
UPDATE public.blends SET name_ar = 'جاردن سيتي', notes_ar = 'شوكولاتة بالحليب - عسل - لمسة خشبية', name_en = 'Garden City', notes_en = 'Milk chocolate - honey - woody touch' WHERE code = 'TRB-218';
UPDATE public.blends SET name_ar = 'قصر البارون', notes_ar = 'ياسمين - كمثرى - عسل', name_en = 'Baron Palace', notes_en = 'Jasmine - pear - honey' WHERE code = 'TRB-219';
UPDATE public.blends SET name_ar = 'القلعة', notes_ar = 'جوز محمص - كراميل داكن - قوام كريمي', name_en = 'The Citadel', notes_en = 'Toasted walnut - dark caramel - creamy body' WHERE code = 'TRB-220';
UPDATE public.blends SET name_ar = 'مرسى علم', notes_ar = 'تفاح أخضر - عسل - حمضية منعشة', name_en = 'Marsa Alam', notes_en = 'Green apple - honey - refreshing acidity' WHERE code = 'TRB-221';
UPDATE public.blends SET name_ar = 'أبو سمبل', notes_ar = 'توت العليق - جوزة الطيب - قرفة', name_en = 'Abu Simbel', notes_en = 'Raspberry - nutmeg - cinnamon' WHERE code = 'TRB-222';
UPDATE public.blends SET name_ar = 'جزيرة النباتات', notes_ar = 'زهور البرتقال - كمثرى - حلاوة العسل', name_en = 'Kitchener''s Island', notes_en = 'Orange blossom - pear - honey sweetness' WHERE code = 'TRB-223';
UPDATE public.blends SET name_ar = 'الكرنك', notes_ar = 'مشمش - عسل السدر - توابل دافئة', name_en = 'Karnak', notes_en = 'Apricot - sidr honey - warm spices' WHERE code = 'TRB-224';
UPDATE public.blends SET name_ar = 'بورفؤاد', notes_ar = 'شوكولاتة داكنة - مكسرات - لمسة ترابية', name_en = 'Port Fuad', notes_en = 'Dark chocolate - nuts - earthy touch' WHERE code = 'TRB-225';
UPDATE public.blends SET name_ar = 'شرم الشيخ', notes_ar = 'أناناس - كراميل - فواكه استوائية', name_en = 'Sharm El Sheikh', notes_en = 'Pineapple - caramel - tropical fruits' WHERE code = 'TRB-226';
UPDATE public.blends SET name_ar = 'المعمورة', notes_ar = 'شاي الياسمين - خوخ - حمضية الليمون', name_en = 'El Maamora', notes_en = 'Jasmine tea - peach - lemon acidity' WHERE code = 'TRB-227';
UPDATE public.blends SET name_ar = 'العين السخنة', notes_ar = 'كراميل - شوكولاتة بالحليب - قوام ناعم', name_en = 'Ain Sokhna', notes_en = 'Caramel - milk chocolate - smooth body' WHERE code = 'TRB-229';
UPDATE public.blends SET name_ar = 'الدرب الأحمر', notes_ar = 'كراميل داكن - فواكه مجففة - مكسرات', name_en = 'El Darb El Ahmar', notes_en = 'Dark caramel - dried fruits - nuts' WHERE code = 'TRB-230';
UPDATE public.blends SET name_ar = 'مراسي', notes_ar = 'شوكولاتة بيضاء - فانيليا - لمسة زهرية', name_en = 'Marassi', notes_en = 'White chocolate - vanilla - floral touch' WHERE code = 'TRB-231';
UPDATE public.blends SET name_ar = 'وسط البلد', notes_ar = 'عنبية - شوكولاتة داكنة - حلاوة', name_en = 'Downtown', notes_en = 'Blueberry - dark chocolate - sweetness' WHERE code = 'TRB-232X';
UPDATE public.blends SET name_ar = 'رأس الحكمة', notes_ar = 'تفاح أخضر - عسل - لمسة زهرية', name_en = 'Ras El Hekma', notes_en = 'Green apple - honey - floral touch' WHERE code = 'TRB-233';
UPDATE public.blends SET name_ar = 'الأزهر', notes_ar = 'تمر - كاكاو - قرفة', name_en = 'Al-Azhar', notes_en = 'Dates - cocoa - cinnamon' WHERE code = 'TRB-234';
UPDATE public.blends SET name_ar = 'قايتباي', notes_ar = 'توت أسود - كراميل مملح - مكسرات', name_en = 'Qaitbay', notes_en = 'Blackberry - salted caramel - nuts' WHERE code = 'TRB-235';
UPDATE public.blends SET name_ar = 'محطة الرمل', notes_ar = 'توت أحمر - كراميل - شوكولاتة', name_en = 'Mahatet El Raml', notes_en = 'Red berries - caramel - chocolate' WHERE code = 'TRB-127';
UPDATE public.blends SET name_ar = 'العجوزة', notes_ar = 'كراميل - تفاح أحمر - مكسرات', name_en = 'Agouza', notes_en = 'Caramel - red apple - nuts' WHERE code = 'TRB-029';
UPDATE public.blends SET name_ar = 'المنيل', notes_ar = 'توت أسود - زهور - حلاوة الشوكولاتة', name_en = 'El Manial', notes_en = 'Blackberry - flowers - chocolate sweetness' WHERE code = 'TRB-030';
UPDATE public.blends SET name_ar = 'رشدي', notes_ar = 'حمضيات - كراميل - تفاح', name_en = 'Roushdy', notes_en = 'Citrus - caramel - apple' WHERE code = 'TRB-031';
UPDATE public.blends SET name_ar = 'سبورتنج', notes_ar = 'توت أسود - شوكولاتة بالحليب - مكسرات', name_en = 'Sporting', notes_en = 'Blackberry - milk chocolate - nuts' WHERE code = 'TRB-032';
UPDATE public.blends SET name_ar = 'الدقي', notes_ar = 'شوكولاتة - فواكه حمراء - توابل', name_en = 'Dokki', notes_en = 'Chocolate - red fruits - spices' WHERE code = 'TRB-037';
UPDATE public.blends SET name_ar = 'سان ستيفانو', notes_ar = 'ليمون - زهور - شاي أسود', name_en = 'San Stefano', notes_en = 'Lemon - flowers - black tea' WHERE code = 'TRB-039';
UPDATE public.blends SET name_ar = 'المنصورة', notes_ar = 'عسل - جوز - حمضية خفيفة', name_en = 'Mansoura', notes_en = 'Honey - walnut - light acidity' WHERE code = 'TRB-046';
UPDATE public.blends SET name_ar = 'طنطا', notes_ar = 'تفاح أخضر - مكسرات - كاكاو', name_en = 'Tanta', notes_en = 'Green apple - nuts - cocoa' WHERE code = 'TRB-049';
UPDATE public.blends SET name_ar = 'عابدين', notes_ar = 'فواكه مجففة - هيل - شوكولاتة داكنة', name_en = 'Abdeen', notes_en = 'Dried fruits - cardamom - dark chocolate' WHERE code = 'TRB-057';
UPDATE public.blends SET name_ar = 'كوم أمبو', notes_ar = 'مشمش مجفف - توابل - زبيب', name_en = 'Kom Ombo', notes_en = 'Dried apricot - spices - raisin' WHERE code = 'TRB-062';
UPDATE public.blends SET name_ar = 'الغردقة', notes_ar = 'أناناس - مانجو - فانيليا', name_en = 'Hurghada', notes_en = 'Pineapple - mango - vanilla' WHERE code = 'TRB-063';
UPDATE public.blends SET name_ar = 'أبيدوس', notes_ar = 'زهور البرتقال - عسل - كاكاو', name_en = 'Abydos', notes_en = 'Orange blossom - honey - cocoa' WHERE code = 'TRB-064';
UPDATE public.blends SET name_ar = 'المهندسين', notes_ar = 'مكسرات - شوكولاتة - حمضية متوازنة', name_en = 'Mohandessin', notes_en = 'Nuts - chocolate - balanced acidity' WHERE code = 'TRB-069';
UPDATE public.blends SET name_ar = 'بورسعيد', notes_ar = 'كراميل - مكسرات - قوام ناعم', name_en = 'Port Said', notes_en = 'Caramel - nuts - smooth body' WHERE code = 'TRB-070';
UPDATE public.blends SET name_ar = 'الواحات البحرية', notes_ar = 'تفاح أخضر - عسل - حمضية مشرقة', name_en = 'Bahariya Oasis', notes_en = 'Green apple - honey - bright acidity' WHERE code = 'TRB-078';
UPDATE public.blends SET name_ar = 'السويس', notes_ar = 'كرز - شوكولاتة داكنة - توابل', name_en = 'Suez', notes_en = 'Cherry - dark chocolate - spices' WHERE code = 'TRB-079';
UPDATE public.blends SET name_ar = 'دندرة', notes_ar = 'شاي أبيض - توت بري - حلاوة', name_en = 'Dendera', notes_en = 'White tea - cranberry - sweetness' WHERE code = 'TRB-080';
UPDATE public.blends SET name_ar = 'النوبة', notes_ar = 'زهور - عسل - خوخ', name_en = 'Nubia', notes_en = 'Flowers - honey - peach' WHERE code = 'TRB-088';
UPDATE public.blends SET name_ar = 'الإسماعيلية', notes_ar = 'كمثرى - جوز - قوام كريمي', name_en = 'Ismailia', notes_en = 'Pear - walnut - creamy body' WHERE code = 'TRB-096';
UPDATE public.blends SET name_ar = 'الخارجة', notes_ar = 'تفاح أخضر - عسل - لمسة تابلية', name_en = 'Kharga', notes_en = 'Green apple - honey - spicy touch' WHERE code = 'TRB-126';
UPDATE public.blends SET name_ar = 'مارينا', notes_ar = 'مكسرات - شوكولاتة - لمسة زهرية خفيفة', name_en = 'Marina', notes_en = 'Nuts - chocolate - light floral touch' WHERE code = 'TRB-160';
UPDATE public.blends SET name_ar = 'سيدي عبد الرحمن', notes_ar = 'شوكولاتة بالحليب - توابل دافئة - كراميل', name_en = 'Sidi Abdel Rahman', notes_en = 'Milk chocolate - warm spices - caramel' WHERE code = 'TRB-161';
UPDATE public.blends SET name_ar = 'ميدان التحرير', notes_ar = 'كراميل - مكسرات - شوكولاتة', name_en = 'Tahrir Square', notes_en = 'Caramel - nuts - chocolate' WHERE code = 'TRB-001';
UPDATE public.blends SET name_ar = 'مصر الجديدة', notes_ar = 'شوكولاتة بالحليب - بندق - قوام كريمي', name_en = 'Heliopolis', notes_en = 'Milk chocolate - hazelnut - creamy body' WHERE code = 'TRB-002';
UPDATE public.blends SET name_ar = 'المقطم', notes_ar = 'تفاح أحمر - فانيليا - حلاوة التوابل', name_en = 'Mokattam', notes_en = 'Red apple - vanilla - spice sweetness' WHERE code = 'TRB-003';
UPDATE public.blends SET name_ar = 'مدينة نصر', notes_ar = 'شوكولاتة - توابل - حمضية الفاكهة', name_en = 'Nasr City', notes_en = 'Chocolate - spices - fruit acidity' WHERE code = 'TRB-004';
UPDATE public.blends SET name_ar = 'شبرا', notes_ar = 'كراميل - بندق - فواكه مجففة', name_en = 'Shoubra', notes_en = 'Caramel - hazelnut - dried fruits' WHERE code = 'TRB-007';
UPDATE public.blends SET name_ar = 'المعادي', notes_ar = 'هيل - زهور البرتقال - توابل', name_en = 'Maadi', notes_en = 'Cardamom - orange blossom - spices' WHERE code = 'TRB-012';
UPDATE public.blends SET name_ar = 'لوران', notes_ar = 'تفاح أخضر - فانيليا - مكسرات', name_en = 'Loran', notes_en = 'Green apple - vanilla - nuts' WHERE code = 'TRB-014';
UPDATE public.blends SET name_ar = 'الأنفوشي', notes_ar = 'ياسمين - برتقال - عسل', name_en = 'Anfoushi', notes_en = 'Jasmine - orange - honey' WHERE code = 'TRB-025';
UPDATE public.blends SET name_ar = 'جليم', notes_ar = 'عنب أسود - شوكولاتة - حلاوة', name_en = 'Glim', notes_en = 'Black grape - chocolate - sweetness' WHERE code = 'TRB-026';
UPDATE public.blends SET name_ar = 'زيزينيا', notes_ar = 'توت أسود - مكسرات - حمضية متوازنة', name_en = 'Zizinia', notes_en = 'Blackberry - nuts - balanced acidity' WHERE code = 'TRB-028';
UPDATE public.blends SET name_ar = 'إدفو', notes_ar = 'توابل شرقية - كراميل - فواكه داكنة', name_en = 'Edfu', notes_en = 'Oriental spices - caramel - dark fruits' WHERE code = 'TRB-033';
UPDATE public.blends SET name_ar = 'سقارة', notes_ar = 'مكسرات محمصة - توابل - لمسة زهرية', name_en = 'Saqqara', notes_en = 'Roasted nuts - spices - floral touch' WHERE code = 'TRB-035';
UPDATE public.blends SET name_ar = 'دهشور', notes_ar = 'شوكولاتة - توت - قوام غني', name_en = 'Dahshur', notes_en = 'Chocolate - berries - rich body' WHERE code = 'TRB-038';
UPDATE public.blends SET name_ar = 'العجمي', notes_ar = 'شاي أسود - جوز الهند - أعشاب عطرية', name_en = 'Agami', notes_en = 'Black tea - coconut - aromatic herbs' WHERE code = 'TRB-050';
UPDATE public.blends SET name_ar = 'كليوباترا', notes_ar = 'شوكولاتة بيضاء - ياسمين - مكسرات', name_en = 'Cleopatra', notes_en = 'White chocolate - jasmine - nuts' WHERE code = 'TRB-051';
UPDATE public.blends SET name_ar = 'المنصورية', notes_ar = 'كراميل - حمضية التفاح - توازن', name_en = 'Mansouria', notes_en = 'Caramel - apple acidity - balance' WHERE code = 'TRB-087';
UPDATE public.blends SET name_ar = 'العلمين', notes_ar = 'خوخ أبيض - شاي - حلاوة', name_en = 'El Alamein', notes_en = 'White peach - tea - sweetness' WHERE code = 'TRB-091';
UPDATE public.blends SET name_ar = 'الأهرامات', notes_ar = 'حمضيات - عسل - توابل معقدة', name_en = 'The Pyramids', notes_en = 'Citrus - honey - complex spices' WHERE code = 'TRB-094';
UPDATE public.blends SET name_ar = 'أبو الهول', notes_ar = 'تفاح أخضر - عسل - حمضية مشرقة', name_en = 'The Sphinx', notes_en = 'Green apple - honey - bright acidity' WHERE code = 'TRB-098';
UPDATE public.blends SET name_ar = 'وادي الملوك', notes_ar = 'مشمش مجفف - فواكه داكنة - قوام حريري', name_en = 'Valley of the Kings', notes_en = 'Dried apricot - dark fruits - silky body' WHERE code = 'TRB-099';
UPDATE public.blends SET name_ar = 'الفسطاط', notes_ar = 'مكسرات - كراميل - شوكولاتة بالحليب', name_en = 'Fustat', notes_en = 'Nuts - caramel - milk chocolate' WHERE code = 'TRB-104';
UPDATE public.blends SET name_ar = 'حتشبسوت', notes_ar = 'زهور - حمضيات - شوكولاتة', name_en = 'Hatshepsut', notes_en = 'Flowers - citrus - chocolate' WHERE code = 'TRB-113';
UPDATE public.blends SET name_ar = 'رمسيس', notes_ar = 'توت أسود - شوكولاتة - مكسرات', name_en = 'Ramses', notes_en = 'Blackberry - chocolate - nuts' WHERE code = 'TRB-114';
UPDATE public.blends SET name_ar = 'توت عنخ آمون', notes_ar = 'برتقال - حمضيات - حلاوة السكر البني', name_en = 'Tutankhamun', notes_en = 'Orange - citrus - brown sugar sweetness' WHERE code = 'TRB-115';
UPDATE public.blends SET name_ar = 'إخناتون', notes_ar = 'توابل - شوكولاتة - فواكه مجففة', name_en = 'Akhenaten', notes_en = 'Spices - chocolate - dried fruits' WHERE code = 'TRB-118';
UPDATE public.blends SET name_ar = 'نفرتيتي', notes_ar = 'كمثرى - عسل - حمضية متوازنة', name_en = 'Nefertiti', notes_en = 'Pear - honey - balanced acidity' WHERE code = 'TRB-120';
UPDATE public.blends SET name_ar = 'نفرتاري', notes_ar = 'خوخ أبيض - زهور - حلاوة فاكهية', name_en = 'Nefertari', notes_en = 'White peach - flowers - fruity sweetness' WHERE code = 'TRB-125';