-- Create the discount_codes table
CREATE TABLE public.discount_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    type text NOT NULL, -- 'percentage' or 'fixed'
    value numeric NOT NULL,
    expires_at timestamp with time zone,
    usage_limit integer,
    usage_count integer DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS and create policies for the new table
ALTER TABLE public.discount_codes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage discount codes"
ON public.discount_codes FOR ALL
USING (get_user_role() = 'admin'::text)
WITH CHECK (get_user_role() = 'admin'::text);

CREATE POLICY "Public can view active discount codes"
ON public.discount_codes FOR SELECT
USING (is_active = true AND (expires_at IS NULL OR expires_at > now()));

-- Add discount-related columns to the orders table
ALTER TABLE public.orders
ADD COLUMN discount_code text,
ADD COLUMN discount_amount numeric;