CREATE TABLE public.loyalty_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_phone TEXT NOT NULL,
  points_change INT NOT NULL,
  reason TEXT,
  admin_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE public.loyalty_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage loyalty logs" ON public.loyalty_log FOR ALL USING (get_user_role() = 'admin');