// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// const SUPABASE_URL = "https://iwjznezwwmvpodedkfqv.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3anpuZXp3d212cG9kZWRrZnF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTU0NDUsImV4cCI6MjA2NzM5MTQ0NX0.kd1v4r7ljdnDgF0bphs2mz62JgarYbWtN12ChGKVSyQ";


//new Supabase ⭐
const SUPABASE_URL = "https://nkrzzfwzvoxsspzyagns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_ZXoLzUW_9kvXEAlQ_BriSg_MruND7sd";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);